# Generated by Django 4.2.5 on 2023-09-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Уроки', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='Lesson',
        ),
    ]
